import Head from 'next/head'
import { Roboto_Mono } from '@next/font/google'
import { NextPage } from 'next'
import { TypeAnimation } from 'react-type-animation'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'

const Consequences: NextPage = () => {
    return (
        <>
            <Head>
                <title>App Store Ethics: The Game</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='w-screen h-screen flex flex-col justify-center items-center bg-primary-bg text-white'>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                        <img src="icon1.png" alt="Icon 1" style={{ width: '50px', height: '50px' }} />
                        <span>Reputation</span>
                    </div>
                    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                        <img src="icon2.png" alt="Icon 2" style={{ width: '50px', height: '50px' }} />
                        <span>Contentment</span>
                    </div>
                    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                        <img src="icon3.png" alt="Icon 3" style={{ width: '50px', height: '50px' }} />
                        <span>Privacy</span>
                    </div>
                    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                        <img src="icon4.png" alt="Icon 4" style={{ width: '50px', height: '50px' }} />
                        <span>Revenue</span>
                    </div>
                </div>
            </div>
        </>
    )
}

export default Consequences