import Head from 'next/head'
import { NextPage } from 'next'
import ConsequencePageSkeleton from '@/components/ConsequencePageSkeleton';

const Consequences: NextPage = () => {
    return (
        <>
            <Head>
                <title>App Store Ethics: The Game</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ConsequencePageSkeleton firstIcon={'First'} secondIcon={'Second'} thirdIcon={'Third'} fourthIcon={'Fourth'}/>
        </>
    )
}

export default Consequences