import Head from 'next/head'
import Image from 'next/image'
import { Inter, Roboto_Mono } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { NextPage } from 'next'
import Title from '@/components/title'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto_Mono({ subsets: ['latin'], variable: '--font-roboto-mono' })

const Home: NextPage =  () => {

  const title: string = 'App Store Ethics: The Game';

  const [counter, setCounter] = useState(0)

  const handleClick = () => {
    setCounter(counter + 1)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='w-screen h-screen flex justify-center items-center bg-primary-bg text-white'>
        <div className={`${roboto.variable} text-4xl font-mono`}>App Store Ethics: The Game</div>
        <div className=''>
            <Title title={title}>
              <h3>hej </h3>
            </Title>
            <button onClick={() => handleClick()}>click me</button>
            <div>{counter}</div>
        </div>
      </div>
    </>
  )
}

export default Home;