import Head from 'next/head'
import Image from 'next/image'
import { Roboto_Mono } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { NextPage } from 'next'


const roboto = Roboto_Mono({ subsets: ['latin'], variable: '--font-roboto-mono' })

export const Home: NextPage =  () => {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='w-screen h-screen flex justify-center items-center bg-primary-bg text-white'>
        <div className={`${roboto.variable} text-4xl font-mono`}>App Store Ethics: The Game</div>
        <div className=''>
        </div>
      </div>
    </>
  )
}
