import Button from '@/components/Button'
import Head from 'next/head'

export default function Main() {
  return (
    <>
        <Head>
            <title>App Store Ethics: The Game</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="grid grid-cols-3 grid-rows-6 place-items-center gap-4 w-screen h-screen justify-center bg-cover bg-center bg-[#1f1f1f] ">
            <div className='flex text-white col-start-2 col-end-2 row-start-1 row-end-1'>
                Hej
            </div>
            <div className="flex col-start-2 col-end-2 row-start-2 row-end-6 w-[80%] h-[100%] bg-white rounded-xl drop-shadow-lg"/>
            <div className='flex col-start-2 col-end-2 row-start-6 row-end-6 w-full h-full justify-evenly items-center'>
                <Button childeren="Decline" link="/main"/>
                <Button childeren="Accept" link="/main"/>
            </div>
        </div>
    </>
  )
}