import Button from '@/components/Button'
import Flashcard from '@/components/Flashcard';
import Head from 'next/head'
import { useState } from 'react';

export default function Main() {

    
    


  return (
    <>
        <Head>
            <title>App Store Ethics: The Game</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <div className="grid grid-cols-3 grid-rows-6 place-items-center gap-4 w-screen h-screen justify-center bg-cover bg-center bg-primary-bg ">
            <div className='flex text-white col-start-2 col-end-2 row-start-1 row-end-1'>
                Hej
            </div>
            <div className="flex justify-center items-center col-start-2 col-end-2 row-start-2 row-end-6">
                <Flashcard/>
            </div>
            <div className='flex col-start-2 col-end-2 row-start-6 row-end-6 w-full h-full justify-evenly items-center'>
                <Button childeren="Decline" link="/main"/>
                <Button childeren="Accept" link="/main"/>
            </div>
        </div>
    </>
  )
}